---

- name: configure junos srx
  hosts: juniper
  gather_facts: false
  tasks:
  - name: load syslog configuration
    junos_config:
      src: files/syslog_config
      comment: syslog config

  - name: configure administrator user
    junos_config:
      src: files/admin_user
      comment: admin user config
  - name: NTP check 
    junos_config:
      src: files/NTP server
      comment: correct NTP server 
      - name: idle timeout check 
    junos_config:
      src: files/idle timeout
      comment: idle timeout confirmed 
