---

- name: Juniper SRX configuration compliance checks 
  hosts: juniper
  gather_facts: false
  tasks:
  - name: Syslog server check
    junos_config:
      src: files/syslog_config
      src_format: set
      comment: Appropriate Syslog server configured 
    register: junos_output
  - debug:
      var: junos_output
      
  - name: print success
    debug:
      msg: Syslog server check - Pass({{ junos_output }})
    when: not junos_output.changed 
   
  - name: print failed
    debug:
      msg: Syslog server check - failed({{ junos_output }})
    when: junos_output.changed 
  
  
    
  - name: Admin credentials 
    junos_config:
      src: files/admin_user
      comment: admin user created and confirmed 
      
    
  - name: NTP check 
    junos_config:
      src: files/NTP server
      comment: correct NTP server 
      
  - name: idle timeout check 
    junos_config:
      src: files/idle timeout
      comment: idle timeout confirmed 
     
