---

- name: Juniper SRX configuration compliance checks 
  hosts: juniper
  gather_facts: false
  connection: local
  tasks:
  - name: Syslog server check
    junos_config:
      src: files/syslog_config
      src_format: set
      comment: Ensure that appropriate Syslog server configured 
    register: junos_output
    diff: true
  - debug:
       var: junos_output

  - debug:
      msg: Syslog server check - This check has passed with the following output({{ junos_output.diff.prepared }})
    when: not junos_output.changed 
   
  - debug:
      msg: Syslog server check - This check has failed with the following output({{ junos_output.diff.prepared }})
    when: junos_output.changed 
  
    
  - name: Admin credentials check
    junos_config:
      src: files/admin_user
      comment: Ensure that Admin user havee been created
    register: junos_output1
    diff: true
  - debug:
       var: junos_output1
  - debug:
      msg: Admin credentials check - This check has passed with the following output({{ junos_output1.diff.prepared }})
    when: not junos_output1.changed 
  
  - debug:
      msg: Admin credentials check - This check has failed with the following output({{ junos_output1.diff.prepared }})
    when: junos_output1.changed 
      
    
  - name: NTP Server check 
    junos_config:
      src: files/NTP server
      comment: Ensure that correct NTP servers has been configured
    register: junos_output2
    diff: true
  - debug:
       var: junos_output2
  - debug:
      msg: NTP Server check  - This check has passed with the following output({{ junos_output2.diff.prepared }})
    when: not junos_output.changed 
 
  - debug:
      msg: NTP Server check  - This check has failed with the following output({{ junos_output2.diff.prepared }})
    when: junos_output2.changed 
      
      
  - name: Idle timeout check 
    junos_config:
      src: files/idle timeout
      comment: Ensure that idle timeout has been confi 
    register: junos_output3
    diff: true
  - debug:
       var: junos_output3
      
  - debug:
      msg: Idle timeout check   - This check has passed with the following output({{ junos_output3.diff.prepared }})
    when: not junos_output.changed 
   
  - debug:
      msg: Idle timeout check   - This check has failed with the following output({{ junos_output3.diff.prepared }})
    when: junos_output.changed 
    
