---

- name: Syslog server check
  hosts: juniper
  gather_facts: false
  tasks:
  - name: load syslog configuration
    junos_config:
      src: files/syslog_config
      comment: Appropriate Syslog server configured 

  - name: Admin credentials 
    junos_config:
      src: files/admin_user
      comment: admin user created and confirmed 
      
  - name: NTP check 
    junos_config:
      src: files/NTP server
      comment: correct NTP server 
      
  - name: idle timeout check 
    junos_config:
      src: files/idle timeout
      comment: idle timeout confirmed 
  
  - name: SSH V2 check 
    junos_config:
      src: files/SSH v2 check 
      comment: SSH V2 protocol correctly configured
  
  - name: AAA check 
    junos_config:
      src: files/AAA server check 
      comment: Appropriate AAA server configured and confirmed 
