---

- name: configure junos srx
  hosts: juniper
  gather_facts: false
  connection: local
  tasks:
  - name: load syslog configuration
    junos_config:
      src: files/syslog_config
      comment: syslog config
    register: task
    diff: true

  - name: print success
    debug:
      msg: syslog configuration - OK
    when: not {{ task.changed }}

  - name: print failed
    debug:
      msg: "{{ task.diff.prepared }}"
    when: "{{ task.changed }}"

  - copy:
      dest: /tmp/diff
      content: "{{ task.diff.prepared }}"
    when: "{{ task.changed }}"
    vars:
      connection: local
      
  - name: configure administrator user
    junos_config:
      src: files/admin_user
      comment: admin user config

